<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'applicationfactorytest' => '/application/unit/factory/FactoryTest.php',
                'applicationtest' => '/application/edge-to-edge/ApplicationTest.php',
                'bankaccountcontrollertest' => '/application/unit/controller/BankAccountControllerTest.php',
                'bankaccountlistcontrollertest' => '/application/unit/controller/BankAccountListControllerTest.php',
                'bankaccountlistviewtest' => '/application/unit/view/BankAccountListViewTest.php',
                'bankaccountmappertest' => '/application/database/mapper/BankAccountMapperTest.php',
                'bankaccounttest' => '/application/unit/model/BankAccountTest.php',
                'bankaccountviewtest' => '/application/unit/view/BankAccountViewTest.php',
                'controllertestcase' => '/application/unit/controller/ControllerTestCase.php',
                'factorytest' => '/framework/factory/FactoryTest.php',
                'frontcontrollertest' => '/framework/frontcontroller/FrontControllerTest.php',
                'hashmaptest' => '/framework/HashMapTest.php',
                'identitymaptest' => '/framework/mapper/IdentityMapTest.php',
                'redirecttobankaccountlisttest' => '/application/unit/controller/RedirectToBankaccountListTest.php',
                'requesttest' => '/framework/http/RequestTest.php',
                'resulttest' => '/framework/view/ResultTest.php',
                'routertest' => '/framework/router/RouterTest.php',
                'testcontroller' => '/framework/_fixture/TestController.php',
                'testmapper' => '/framework/_fixture/TestMapper.php',
                'testview' => '/framework/_fixture/TestView.php',
                'viewtest' => '/framework/view/ViewTest.php',
                'webtest' => '/application/end-to-end/WebTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd