<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'bankaccount\\framework\\controller\\controllerinterface' => '/controller/Interface.php',
                'bankaccount\\framework\\controller\\exception' => '/controller/Exception.php',
                'bankaccount\\framework\\exception\\exception' => '/exception/Interface.php',
                'bankaccount\\framework\\exception\\outofboundsexception' => '/exception/OutOfBounds.php',
                'bankaccount\\framework\\exception\\runtimeexception' => '/exception/Runtime.php',
                'bankaccount\\framework\\factory\\exception' => '/factory/Exception.php',
                'bankaccount\\framework\\factory\\factory' => '/factory/Factory.php',
                'bankaccount\\framework\\factory\\factoryinterface' => '/factory/Interface.php',
                'bankaccount\\framework\\frontcontroller' => '/FrontController.php',
                'bankaccount\\framework\\hashmap' => '/HashMap.php',
                'bankaccount\\framework\\http\\request' => '/http/Request.php',
                'bankaccount\\framework\\http\\response' => '/http/Response.php',
                'bankaccount\\framework\\mapper\\exception' => '/mapper/Exception.php',
                'bankaccount\\framework\\mapper\\identitymap' => '/mapper/IdentityMap.php',
                'bankaccount\\framework\\router\\exception' => '/router/Exception.php',
                'bankaccount\\framework\\router\\router' => '/router/Router.php',
                'bankaccount\\framework\\testing\\result' => '/testing/Result.php',
                'bankaccount\\framework\\testing\\viewtestcase' => '/testing/ViewTestCase.php',
                'bankaccount\\framework\\view\\redirect' => '/view/Redirect.php',
                'bankaccount\\framework\\view\\result' => '/view/Result.php',
                'bankaccount\\framework\\view\\view' => '/view/View.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd